"""documents chunks ingest_jobs

Revision ID: e2a9ffce7300
Revises: 
Create Date: 2026-05-25 20:53:51.707430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a9ffce7300'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_path', sa.String(), nullable=False),
    sa.Column('parsed_md_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_owner_user_id'), 'documents', ['owner_user_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('heading_path', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(), nullable=False),
    sa.Column('token_len', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_table('ingest_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage_detail', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_jobs_document_id'), 'ingest_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_owner_user_id'), 'ingest_jobs', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_jobs_owner_user_id'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_document_id'), table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_documents_owner_user_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
